name: CI
on: [push]
jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository and change directory to frontend
              uses: actions/checkout@v2

            - name: ğŸ—‚ï¸ Install
              run: |
                  cd frontend
                  npm install

            - name: ğŸ”¨ Build
              run: |
                  cd frontend
                  npm run build

            - name: ğŸ§ª Test  npm test
              run: |
                  cd frontend
                  npm test
